@file:OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)

package app.vkturn.wingsv

import kotlinx.serialization.Serializable
import kotlinx.serialization.protobuf.ProtoNumber

/**
 * Kotlin mirror of `3x-ui/wingsv/proto/wingsv.proto` generated by hand.
 *
 * Only the fields we actually consume are declared — unknown proto fields
 * are skipped by [kotlinx.serialization.protobuf.ProtoBuf] when
 * `ignoreUnknownKeys` is enabled on the codec. Optional `proto3` fields
 * map to nullable Kotlin types; repeated fields stay as [List].
 */

@Serializable
internal data class WingsvConfig(
    @ProtoNumber(1) val ver: Int = 0,
    @ProtoNumber(2) val type: Int = 0,                // ConfigType enum (VK=1, XRAY=2, AMNEZIAWG=3, ...)
    @ProtoNumber(3) val turn: WingsvTurn? = null,
    @ProtoNumber(4) val wg: WingsvWireGuard? = null,
    @ProtoNumber(5) val backend: Int = 0,
    // @ProtoNumber(6) val xray: ... — skipped, VLESS import postponed
    @ProtoNumber(7) val awg: WingsvAmneziaWg? = null,
    // @ProtoNumber(8) val appRouting — skipped
    @ProtoNumber(9) val wbStream: WingsvWbStream? = null,
)

@Serializable
internal data class WingsvEndpoint(
    @ProtoNumber(1) val host: String = "",
    @ProtoNumber(2) val port: Int = 0,
)

@Serializable
internal data class WingsvCidr(
    @ProtoNumber(1) val addr: ByteArray = ByteArray(0),
    @ProtoNumber(2) val prefix: Int = 0,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is WingsvCidr) return false
        return prefix == other.prefix && addr.contentEquals(other.addr)
    }
    override fun hashCode(): Int = 31 * prefix + addr.contentHashCode()
}

@Serializable
internal data class WingsvTurn(
    @ProtoNumber(1) val endpoint: WingsvEndpoint? = null,
    @ProtoNumber(2) val link: String = "",
    @ProtoNumber(3) val threads: Int? = null,
    @ProtoNumber(4) val useUdp: Boolean? = null,
    @ProtoNumber(5) val noObfuscation: Boolean? = null,
    @ProtoNumber(6) val localEndpoint: WingsvEndpoint? = null,
    @ProtoNumber(7) val host: String = "",
    @ProtoNumber(8) val port: Int? = null,
    @ProtoNumber(9) val sessionMode: Int = 0,         // TurnSessionMode enum
    @ProtoNumber(10) val links: List<String> = emptyList(),
    @ProtoNumber(11) val linkSecondary: String = "",
    @ProtoNumber(12) val credsGroupSize: Int? = null,
)

@Serializable
internal data class WingsvWireGuard(
    @ProtoNumber(1) val iface: WingsvInterface? = null,
    @ProtoNumber(2) val peer: WingsvPeer? = null,
    @ProtoNumber(3) val endpoint: WingsvEndpoint? = null,
)

@Serializable
internal data class WingsvInterface(
    @ProtoNumber(1) val privateKey: ByteArray = ByteArray(0),
    @ProtoNumber(2) val addrs: List<String> = emptyList(),
    @ProtoNumber(3) val dns: List<String> = emptyList(),
    @ProtoNumber(4) val mtu: Int? = null,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is WingsvInterface) return false
        return mtu == other.mtu && addrs == other.addrs && dns == other.dns &&
                privateKey.contentEquals(other.privateKey)
    }
    override fun hashCode(): Int {
        var r = privateKey.contentHashCode()
        r = 31 * r + addrs.hashCode(); r = 31 * r + dns.hashCode(); r = 31 * r + (mtu ?: 0)
        return r
    }
}

@Serializable
internal data class WingsvPeer(
    @ProtoNumber(1) val publicKey: ByteArray = ByteArray(0),
    @ProtoNumber(2) val presharedKey: ByteArray = ByteArray(0),
    @ProtoNumber(3) val allowedIps: List<WingsvCidr> = emptyList(),
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is WingsvPeer) return false
        return allowedIps == other.allowedIps &&
                publicKey.contentEquals(other.publicKey) &&
                presharedKey.contentEquals(other.presharedKey)
    }
    override fun hashCode(): Int {
        var r = publicKey.contentHashCode()
        r = 31 * r + presharedKey.contentHashCode(); r = 31 * r + allowedIps.hashCode()
        return r
    }
}

@Serializable
internal data class WingsvAmneziaWg(
    @ProtoNumber(1) val awgQuickConfig: String = "",
)

@Serializable
internal data class WingsvWbStream(
    @ProtoNumber(1) val roomId: String = "",
    @ProtoNumber(2) val exchangeViaVkTurn: Boolean = false,
    @ProtoNumber(3) val e2eEnabled: Boolean = false,
    @ProtoNumber(4) val e2eSecret: ByteArray = ByteArray(0),
    @ProtoNumber(5) val displayName: String = "",
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is WingsvWbStream) return false
        return roomId == other.roomId && exchangeViaVkTurn == other.exchangeViaVkTurn &&
                e2eEnabled == other.e2eEnabled && displayName == other.displayName &&
                e2eSecret.contentEquals(other.e2eSecret)
    }
    override fun hashCode(): Int {
        var r = roomId.hashCode()
        r = 31 * r + exchangeViaVkTurn.hashCode(); r = 31 * r + e2eEnabled.hashCode()
        r = 31 * r + displayName.hashCode(); r = 31 * r + e2eSecret.contentHashCode()
        return r
    }
}

/** Enum mappings from the proto — duplicated as Kotlin ints for clarity. */
internal object Wingsv {
    // ConfigType
    const val CONFIG_TYPE_VK = 1
    const val CONFIG_TYPE_XRAY = 2
    const val CONFIG_TYPE_AMNEZIAWG = 3
    const val CONFIG_TYPE_ALL = 4
    const val CONFIG_TYPE_WB_STREAM = 7

    // BackendType
    const val BACKEND_VK_TURN_WIREGUARD = 1
    const val BACKEND_XRAY = 2
    const val BACKEND_AMNEZIAWG = 3
    const val BACKEND_WIREGUARD = 4
    const val BACKEND_AMNEZIAWG_PLAIN = 5
    const val BACKEND_WB_STREAM = 6

    // TurnSessionMode
    const val TURN_SESSION_AUTO = 1
    const val TURN_SESSION_MAINLINE = 2
    const val TURN_SESSION_MUX = 3
}
